http:
  serversTransports:
    insecure-skipverify:
      insecureSkipVerify: true

  routers:
    images:
      rule: Host(`images.marcel-sigl.dev`)
      entryPoints: [web]
      service: images-svc
    proxmox:
      rule: Host(`proxmox.marcel-sigl.dev`)
      entryPoints: [web]
      service: proxmox-svc

  services:
    proxmox-svc:
      loadBalancer:
        servers:
          - url: http://10.0.0.1:8006

    images-svc:
      loadBalancer:
        servers:
          - url: http://10.0.0.11:2283
