http:
  routers:
    ha:
      rule: Host(`ha.marcel-sigl.dev`)
      entryPoints:
        - websecure
      middlewares:
        - local-only
      service: ha-svc
      tls:
        certResolver: myresolver

  services:
    ha-svc:
      loadBalancer:
        serversTransport: insecure-skipverify
        servers:
          - url: "http://10.0.0.13:8123"

serversTransports:
  pve-transport:
    insecureSkipVerify: true
