# Optional, but nice: default log level
loglevel: info

# Route all subdomains of your domain to Traefik
ingress:
  - hostname: "*.marcel-sigl.dev"
    service: http://traefik:80
    originRequest:
      disableChunkedEncoding: true
  - service: http_status:404

